### ISSUE TITLE
Some way of providing stable object links to "latest" spec

### ISSUE THREAD

**Issue by peteyak** [nsip/SIFConceptualModel#2]
It would be useful to be able to create a URL link to the "current" spec at the individual object level, rather than a link requiring specific version number. Nick suggests doing this via apache redirects, which are in the province of John Lovell.

**Comment by opoudjis** [comment]
@peteyak, discuss this with @LindaNSIP soon.

**Comment by peteyak** [comment]
Closing - duplicate of nsip/NSIP-Internal#341
